name: Build AIX

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build extension
        uses: mit-cml/appinventor-sources-action@master
        with:
          command: extensions
      - name: Locate AIX
        run: |
          find . -type f -name "*.aix" -print
          mkdir -p dist
          find . -type f -name "*.aix" -exec cp {} dist/ \;
      - name: Upload AIX
        uses: actions/upload-artifact@v4
        with:
          name: GikkuTransparentWebView-aix
          path: dist/*.aix
